[package]
name = "gh-actions-scaler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
dirs = "5.0.1"
log = "0.4.22"
pretty_env_logger = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10.0"
